export const ALL_ALFAJOR = 'ALL_ALFAJOR';
export const GET_ALFAJOR = 'GET_ALFAJOR';
export const ADD_ALFAJOR = 'ADD_ALFAJOR';
export const ADD_ALFAJOR_ERROR = 'ADD_ALFAJOR_ERROR';
export const EDIT_ALFAJOR = 'EDIT_ALFAJOR';
export const EDIT_ALFAJOR_ERROR = 'EDIT_ALFAJOR_ERROR';
export const DELETE_ALFAJOR = 'DELETE_ALFAJOR';

export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';

export const IDIOMA_EDIT = 'IDIOMA_EDIT';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const KEEP_IMAGE = 'KEEP_IMAGE';
export const GET_IMAGE = 'GET_IMAGE';
