export const ADD_ALFAJOR = 'ADD_ALFAJOR';
export const EDIT_ALFAJOR = 'EDIT_ALFAJOR';
export const DELETE_ALFAJOR = 'DELETE_ALFAJOR';
export const ALL_ALFAJOR = 'ALL_ALFAJOR';

export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';
